[features]
seeds = false
skip-lint = false
[programs.localnet]
token_update = "7oTo4ZQQwPSpErvAEw75bPWMbRULiBfEFeeA69i6dU8w"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/rogaldh/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
